name: My First Pipeline

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello Cipri pipeline test1"

      - name: Show files
        run: ls
      
      - name: Show files 1
        run: ls -la 

      - name: Show current directory
        run: pwd

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
     
      - name: Terraform Fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
